### PR TITLE
refactor: standardise profile lookups

### PR DESCRIPTION
**Pull request by roleyfoley**
## Intent of Change

- Bug fix (non-breaking change which fixes an issue)
- Refactor (non-breaking change which improves the structure or operation of the implementation)

## Description

- Adds a standard function and process for looking up profiles assigned to components

Profiles essentially have two lookup configurations
- Typed: which breaks the profile into typed sections within a profile. This is generally based on the component type or the tier component name of a component
- Explicit: which applies the same profile to all components

The generic function supports both types and uses the lookup process to find the appropriate profile

- Adds some additional profiles found during this update to the ec2 components
- Removes some of the global variables from setContext to reduce the scoping issues with global vars

## Motivation and Context

When working with profiles it was difficult to figure out where they were used and how they could be modified. This creates standard ways to configure profiles to make this easier

## How Has This Been Tested?

Tested locally and with test suite

### Prerequisite PRs:

- None

### Dependent PRs:

- https://github.com/hamlet-io/engine-plugin-aws/pull/330
- https://github.com/hamlet-io/engine-plugin-azure/pull/261

### Consumer Actions:

- None

### CODE REVIEW

**Comment by ml019** [comment]
@roleyfoley keen to get this and its dependents merged. Would you be able to respond to my query and rebase?

Thanks

**Comment by roleyfoley** [comment]
> @roleyfoley keen to get this and its dependents merged. Would you be able to respond to my query and rebase?
> 
> Thanks

rebase done but I couldn't find your comments anywhere

**Comment by ml019** [comment]
@roleyfoley sorry. I hadn't pressed submit on my review but github shows it like you have so I didn't tweak to the fact it was still in draft.

**Comment by roleyfoley** [comment]
@ml019 fixed up and good to go. I don't think the override was actually used by the components. But it was included to align with the other profiles

**Review by ml019 — APPROVED** [review]

**Pull request merged**
