### PR TITLE
feat(lambda): remove constraint on runtime

### PR DESCRIPTION
**Pull request by ken9ross**
## Intent of Change

- New feature (non-breaking change which adds functionality)

## Description
Remove value list on runtime engine selection

## Motivation and Context
Fixes https://github.com/hamlet-io/engine/issues/1640

## How Has This Been Tested?
Locally

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

### CODE REVIEW

**Comment by ken9ross** [comment]
This seems so simple, that I don't understand raising a new request rather than doing it as part of #1638. Have I missed something in the requirement?

**Comment by roleyfoley** [comment]
> This seems so simple, that I don't understand raising a new request rather than doing it as part of #1638. Have I missed something in the requirement?

The technical implementation is super simple the discussion on if we should do it not was intended for the ticket. That hasn't really happened yet.

**Comment by ml019** [comment]
I'm wondering if we need an option to provide a value set and flag a warning rather than an error if the value provided is outside the set. That way we don't stop new values being used, but do assist when the value has a typo.

So basically extending the current logic that checks for values to check if say an `AdditionalValues : true` attribute is present and set to true. In this case, allow a user defined value but warn of its use. We can still perform other checks such as type conformance.

I'm reflecting the pattern used in JSON schema where `additionalProperties : true` controls whether unspecified properties can be present on an object.

**Comment by roleyfoley** [comment]
> I'm wondering if we need an option to provide a value set and flag a warning rather than an error if the value provided is outside the set. That way we don't stop new values being used, but do assist when the value has a typo.
> 
> So basically extending the current logic that checks for values to check if say an `AdditionalValues : true` attribute is present and set to true. In this case, allow a user defined value but warn of its use. We can still perform other checks such as type conformance.
> 
> I'm reflecting the pattern used in JSON schema where `additionalProperties : true` controls whether unspecified properties can be present on an object.

Yeah I like it!

**Comment by roleyfoley** [comment]
Closing this PR in favour of completing the conversion in https://github.com/hamlet-io/engine/issues/1640 which could involve changes to the engine instead.

**Pull request closed without merging**
