### PR TITLE
Fix/schemageneration

### PR DESCRIPTION
**Pull request by RossMurr4y**
## Description

Updates schema generation with the `getCLO~()` functions.

## Motivation and Context

Schema generation broken.

## How Has This Been Tested?

Locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

### CODE REVIEW

**Comment by RossMurr4y** [comment]
@roleyfoley would you be able to take a quick look at this when you have a second?

The changes I've made fix the [current problem with the CI](https://github.com/hamlet-io/docs/runs/2206151191?check_suite_focus=true), but they expose a deeper issue outlined below.

When a schema is created into a directory it already exists, the outputhandler seems to think that the filename its about to create is an the contents of the entire schema.

When deleting all the schemas in the output directory and then re-trying this, it works fine.

Cmd: `hamlet -i mock -p shared schema create-schemas -o .`

Error:

```bash
Exception in thread "main" FreeMarker template error:
Expression has thrown an unchecked exception; see the cause exception.
The blamed expression:
==> toCMDB(
                formatAbsolutePath(
                    (fileProperties["directory"])!"",
                    (fileProperties["filename"])!""
                ),
                content,
                {
                    "Format" : fileFormat
                }
            )  [in template "shared/outputhandlers/write_to_cmdb/outputhandler.ftl" at line 28, column 26]

----
```

I've tried throwing a debug into the outputhandler, which shows me that the fileProperties for the output file are... wrong. Instead of listing a filename correctly, it prints the content of the entire schema...


```freemarker
[#function shared_outputhandler_write_to_cmdb properties content ]

...
    [#if !(getCLODeploymentOutputType() == "contract" )]
        [#stop getJSON(fileProperties)]
    [/#if]

...

[#if ((fileProperties["directory"])!"")?has_content &&
            ((fileProperties["filename"])!"")?has_content ]

        [#local result = toCMDB(
            formatAbsolutePath(
                (fileProperties["directory"])!"",
                (fileProperties["filename"])!""
            ),
            content,
            {
                "Format" : fileFormat
            }
        )]
    [/#if]
    [#return properties]
[/#if]
```

Which returns:

```bash
(Fatal) ! template engine managed exception encountered. Details follow...

{"filename" : "{\n  \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n  \"type\": \"object\",\n  \"definitions\": {\n    \"baseline\": {\n      \"patternProperties\": {\n        \"^[A-Za-z_][A-Za-z0-9_]*$\": {\n          \"additionalProperties\": false,\n          \"properties\": {\n            \"Instances\": {\n              \"patternProperties\": {\n                \"^[A-Za-z_][A-Za-z0-9_]*$\": {\n                  \"additionalProperties\": false,\n                  \"properties\": {\n                    \"DeploymentUnits\": {\n  ...
```

I'm a bit stumped!

**Comment by roleyfoley** [comment]
Just reproduced that issue and will take a look. That's properly weird. I suspect its something in generation contract that is a bit out

**Comment by RossMurr4y** [comment]
This appears to have something to do with the output type filenames. Schemas should be of the format: _schema-<type>-<instance>-schema.json_ but [I've just seen that the CI has just omitted the `type` from the name altogether](https://github.com/hamlet-io/docs/commit/99c034003cd83e863c95f2563b2b7a90aa692a36).

**Comment by roleyfoley** [comment]
- Output file naming should be fixed in https://github.com/hamlet-io/engine/pull/1606 
- The filename change when running on files that already have content fixed in https://github.com/hamlet-io/executor-bash/pull/183

**Comment by RossMurr4y** [comment]
underlying issues resolved, now ready for review

**Pull request merged**
