### PR TITLE
fix: define deploymentgroups for schemas

### PR DESCRIPTION
**Pull request by RossMurr4y**
## Description

The introduction of validation for DeploymentGroups at runtime has
caused schema generation to fail. Unless a DeploymentGroup is defined
within a blueprint, the option is invalid as a commandLineOption.

This commit introduces definitions for the groups used for JSONSchema
generation - component, reference, module and attributeset.

It also adds schema generation into the Jenkins pipeline to act as a test for catching this sort of thing in the future.

## Motivation and Context

#1576 

## How Has This Been Tested?

Locally - can now generate schemas the same as before introduction of #1576 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves the structure or operation of the implementation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Followup Actions

- [x] None

## Checklist:

- [ ] My change requires a change to the [documentation](https://github.com/hamlet-io/docs).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] None of the above.

### CODE REVIEW

**Comment by roleyfoley** [comment]
I think its probably better that we move these checks to only run in the deployment entrance. Having extra deployment groups to work around the schema setup doesn't feel right. 

As an extra step they should probably be their own command line options to make it easier to follow.

**Review by roleyfoley — CHANGES_REQUESTED** [review]
I think its probably better that we move these checks to only run in the deployment entrance. Having extra deployment groups to work around the schema setup doesn't feel right. 

As an extra step they should probably be their own command line options to make it easier to follow.

**Comment by RossMurr4y** [comment]
> I think its probably better that we move these checks to only run in the deployment entrance. Having extra deployment groups to work around the schema setup doesn't feel right.

I've moved it over now.

> As an extra step they should probably be their own command line options to make it easier to follow.

Note sure what you are referring to. Do you mean that the schema group/unit should be a unique set of commandLineOptions so as to be distinct from component generation? Wont that be applicable to pretty much anything we generate that isn't components?

**Comment by roleyfoley** [comment]
> Note sure what you are referring to. Do you mean that the schema group/unit should be a unique set of commandLineOptions so as to be distinct from component generation? Wont that be applicable to pretty much anything we generate that isn't components?

Yeah essentially as the commandline option says the value you are using is  deploymentUnit and deploymentGroup which aren't actually relevant to what you are doing. So instead of overloading one option and making it difficult to validate we should validate each one as required.

**Review by roleyfoley — APPROVED** [review]

**Pull request merged**
