### PR TITLE
chore: add node 14 support for lambda

### PR DESCRIPTION
**Pull request by ml019**
## Intent of Change

- New feature (non-breaking change which adds functionality)

## Description
Add the specific runtime value needed for using node 14 with lambda.

## Motivation and Context
Keeping up with AWS ...

## How Has This Been Tested?
Local template generation

## Followup Actions
- [x] None

### CODE REVIEW

**Comment by roleyfoley** [comment]
Should we just remove this value? seems like this is a bit of a maintenance burden, that we could fix with a note on the component or set a description. 


`For supported values see the Identifier value here ( https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html )`

**Review by roleyfoley — CHANGES_REQUESTED** [review]
Should we just remove Values here? seems like this is a bit of a maintenance burden, that we could fix with a note on the component or set a description. 


`For supported values see the Identifier value here ( https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html )`

**Comment by ml019** [comment]
@roleyfoley I think a sanity check that we are ok with the new version is still worthwhile. They are not changing so fast we can't keep up.

**Comment by roleyfoley** [comment]
I can see where you are coming from at the hamlet development side, but as a user I think that just gets in the way, and has a potential impact on that first 20 minute window of using hamlet. 

if we miss a type then people will get a bad impression that we aren't keeping up. 

Are we actually doing anything to test that each version works? does any of our code actually worry about what the version is?

**Comment by ml019** [comment]
Equally, if they get the value wrong, they have to wait until stack generation time. 

I've raised https://github.com/hamlet-io/engine/issues/1640 to cover off the broader issue/discussion with the team.

In the interim, I'd like to get this in so I can deploy stuff for ICS.

**Review by roleyfoley — APPROVED** [review]

**Pull request merged**
