### PR TITLE
chore: remove datapipeline support

### PR DESCRIPTION
**Pull request by roleyfoley**
## Intent of Change

- Refactor (non-breaking change which improves the structure or operation of the implementation)

## Description

- Remove the datapipeline component as it is no longer used

## Motivation and Context

Addresses https://github.com/hamlet-io/engine/issues/1996
The datapipeline component has not been used and represents a component that has been depreated. 

## How Has This Been Tested?

Tested locally

### Prerequisite PRs:

- None

### Dependent PRs:

- None

### Consumer Actions:

- None

### CODE REVIEW

**Comment by ml019** [comment]
@roleyfoley understand we haven't used this since PSMA. Do you think there are better ways of doing this? Still feels like a valuable component to have.

**Comment by roleyfoley** [comment]
Heaps of better was than AWS data pipeline. 

- Step functions
- Jenkins pipelines 
- Dedicated ETL tools 

Since data pipeline is purely based on Ec2 instances and specific data tools I would say that we move to replacing it with a generic workflow component using step functions instead. If someone wants to build out specific ETL tools they can.

**Comment by ml019** [comment]
Ok - did you want me to approve the draft PRs, or will you move them to review?

**Comment by roleyfoley** [comment]
Since its a breaking change was going to wait until this release got through before adding this

**Pull request merged**
